
CREATE VIEW ITMPCKVW AS 
SELECT P.AMBKOD,P.ITNBR,P.AMBTAN,P.KKOD,P.KMIK,
P.PKOD,P.PKMIK, P.PKSIR,P.KPKKOD,P.KPMIK,P.SPKOD,
P.SPMIK,P.MAMBKOD,P.MKKOD, P.MPKOD,P.MSPKOD,P.MKPKOD,
P.REVNO,P.REVTAR, ID1.BRMAG AS KTBRMAG,ID1.BRMHC AS KTBRMHC, 
ID1.AGOB AS KTAGOB,ID1.HCOB AS KTHCOB,   
ID2.BRMAG AS PLBRMAG, ID2.BRMHC AS PLBRMHC,
ID2.AGOB AS PLAGOB,ID2.HCOB AS PLHCOB, 
ID3.BRMAG AS KPBRMAG,ID3.BRMHC AS KPBRMHC,
ID3.AGOB AS KPAGOB, ID3.HCOB AS KPHCOB,ID4.BRMAG AS SPBRMAG,
ID4.BRMHC AS SPBRMHC   , ID4.AGOB AS SPAGOB,ID4.HCOB AS SPHCOB,
ID1.PAPTIP AS KPAPTIP, ID2.PAPTIP AS PPAPTIP 
FROM ITMPACK P 
LEFT OUTER JOIN ITEMDIM ID1 ON P.KKOD=ID1.ITNBR 
LEFT OUTER JOIN ITEMDIM ID2 ON P.PKOD=ID2.ITNBR 
LEFT OUTER JOIN ITEMDIM ID3 ON P.KPKKOD=ID3.ITNBR 
LEFT OUTER JOIN ITEMDIM ID4 ON P.SPKOD=ID4.ITNBR       