
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[PLANTPRMJL] 
AS
SELECT PLANTPRM.CANB, PLANTPRM.B9CD, PLANTPRM.SDRODID, 
PLANTPRM.SDRODCD, KONTRTPF.SRKT, KONTRTPF.CUST, 
KONTRTPF.ITEM, KONTRTPF.KNTRT, KONTRTPF.SHIPTO, KONTRTPF.BZMITM, 
KONTRTPF.KAPI,KONTRTPF.REFADI, KONTRTPF.AMBKOD, KONTRTPF.HOUSE , PLANTPRM.KUMLEVEL,
Plantprm.cust_seq
FROM PLANTPRM , KONTRTPF 
WHERE PLANTPRM.CANB=KONTRTPF.CUST 
	AND PLANTPRM.B9CD=KONTRTPF.SHIPTO
GO

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

