drop table EDIMST

Create Table EDIMST
(
SENDER	nvarchar(	35		 	),
RECEIVER	nvarchar(	35		 	),
MSGNUM	nvarchar(	35		 	),
MSGDTM	numeric(	8	,	0	),
MSGTX1	nvarchar(	70		 	),
MSGTX2	nvarchar(	70		 	),
MSGTX3	nvarchar(	70		 	),
DUNSID	nvarchar(	35		 	),
PUSNO	nvarchar(	22		 	),
MISSUER	nvarchar(	35		 	),
PLANTID	nvarchar(	35		 	),
CUSITM	nvarchar(	35		 	),
GATEID	nvarchar(	25		 	),
CONTNO	nvarchar(	35		 	),
CUMQTY	numeric(	15	,	0	),
CUMREF	nvarchar(	35		 	),
CUMDTE	numeric(	8	,	0	),
DELTYP	nvarchar(	3		 	),
DELQTY	numeric(	15	,	0	),
DELDTE	numeric(	8	,	0	),
NETQTY	numeric(	15	,	0	),
NETDTE	numeric(	8	,	0	),
RECCNT	numeric(	3	,	0	),
MPXITM	nvarchar(	15		 	),
MPXCUM	numeric(	15	,	3	),
MPXCMT	datetime,
MPXCUS	nvarchar(	7			),
MPXCUSSEQ int,
MPXWHS	nvarchar(	4		 	),
MPXPRC	numeric(	15	,	3	),
MPXCUR	nvarchar(	3		 	),
MPXAMB	nvarchar(	10		 	),
MPXKADT	numeric(	7	,	0	),
MPXNAKL	nvarchar(	10		 	),
MPXPLNM	nvarchar(	35		 	),
HATADRM	nvarchar(	1		 	),
MSGSTAT	nvarchar(	1		 	),
HATAMSG	nvarchar(	150		 	),
CRDDTE	numeric(	8	,	0	),
CRDTIM	numeric(	6	,	0	),
CRDUSR	nvarchar(	10		 	),
MATHNDCD	nvarchar(	15		 	),
KANBANNO	nvarchar(	15		 	),
L3PREF	nvarchar(	20		 	),
USERF1	nvarchar(	15		 	),
USERF2	nvarchar(	35		 	),
USERF3	nvarchar(	35		 	),
USERF4	numeric(	8	,	0	),
USERF5	numeric(	15	,	0	),
USERF6	numeric(	15	,	0	),
KUMLEVEL numeric(1,0) default (0) 
)