USE [SLTTR_App]
GO
/****** Object:  Table [dbo].[SHPPACK]    Script Date: 08/20/2009 21:31:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SHPPACK](
	[SHPNO] [numeric](7, 0) NULL,
	[PICKNO] [numeric](7, 0) NULL,
	[PICKDT] [datetime] NULL,
	[SHIPTO] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KAPI] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ITNBR] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CUST] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHIPNM] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PUSNO] [nvarchar](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SEVKTAR] [datetime] NULL,
	[IRSNO] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AMBKOD] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHIPMIK] [numeric](17, 3) NULL,
	[KKOD] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KSAY] [numeric](7, 0) NULL,
	[KMIK] [numeric](7, 0) NULL,
	[HKSAY] [numeric](7, 0) NULL,
	[PKOD] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PSAY] [numeric](7, 0) NULL,
	[PKMIK] [numeric](7, 0) NULL,
	[PKSIR] [numeric](7, 0) NULL,
	[SPKOD] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPMIK] [numeric](7, 0) NULL,
	[KPKOD] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KPMIK] [numeric](7, 0) NULL,
	[NETAGR] [numeric](17, 3) NULL,
	[BRTAGR] [numeric](17, 3) NULL,
	[HACIM] [numeric](17, 3) NULL,
	[AGOB] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCOB] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STKOB] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KAP_EN] [numeric](7, 0) NULL,
	[KAP_BOY] [numeric](7, 0) NULL,
	[KAP_YUK] [numeric](7, 0) NULL,
	[YUKLADR] [numeric](3, 0) NULL,
	[TRNCODE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ASNDRM] [numeric](1, 0) NULL,
	[ETKDRM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ASNNO] [numeric](10, 0) NULL,
	[ASNMIK] [numeric](17, 3) NULL,
	[USERF1] [numeric](10, 0) NULL,
	[USERF2] [numeric](10, 0) NULL,
	[USERF3] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[USERF4] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[USERF5] [numeric](17, 3) NULL,
	[CRDDTE] [datetime] NULL,
	[CRDTIM] [numeric](6, 0) NULL,
	[CRDUSR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INVNO] [numeric](10, 0) NULL,
	[INVDRM] [numeric](1, 0) NULL,
	[CHEPDRM] [numeric](1, 0) NULL,
	[CHEPNO] [numeric](10, 0) NULL,
	[ILKPALETNO] [numeric](7, 0) NULL,
	[ILKKUTUNO] [numeric](7, 0) NULL,
	[WHSE] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MURNKOD] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MURNTNM] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FATNO] [numeric](10, 0) NULL CONSTRAINT [DF_SHPPACK_FATNO]  DEFAULT ((0)),
	[FATDRM] [numeric](1, 0) NULL CONSTRAINT [DF_SHPPACK_FATDRM]  DEFAULT ((0))
) ON [PRIMARY]
