CREATE TABLE [dbo].[tr_co_ship](
	[co_num] [dbo].[CoNumType] NOT NULL,
	[co_line] [dbo].[CoLineType] NOT NULL CONSTRAINT [DF_tr_co_ship_co_line]  DEFAULT ((0)),
	[co_release] [dbo].[CoReleaseType] NOT NULL CONSTRAINT [DF_tr_co_ship_co_release]  DEFAULT ((0)),
	[date_seq] [dbo].[DateSeqType] NOT NULL CONSTRAINT [DF_tr_co_ship_date_seq]  DEFAULT ((0)),
	[qty_invoiced] [dbo].[QtyUnitType] NULL CONSTRAINT [DF_tr_co_ship_qty_invoiced]  DEFAULT ((0)),
	[ship_date] [dbo].[DateType] NOT NULL,
	[qty_shipped] [dbo].[QtyUnitType] NULL CONSTRAINT [DF_tr_co_ship_qty_shipped]  DEFAULT ((0)),
	[qty_returned] [dbo].[QtyUnitType] NULL CONSTRAINT [DF_tr_co_ship_qty_returned]  DEFAULT ((0)),
	[cost] [dbo].[CostPrcType] NULL CONSTRAINT [DF_tr_co_ship_cost]  DEFAULT ((0)),
	[price] [dbo].[CostPrcType] NULL CONSTRAINT [DF_tr_co_ship_price]  DEFAULT ((0)),
	[unit_weight] [dbo].[UnitWeightType] NULL CONSTRAINT [DF_tr_co_ship_unit_weight]  DEFAULT ((0)),
	[by_cons] [dbo].[ListYesNoType] NULL CONSTRAINT [DF_tr_co_ship_by_cons]  DEFAULT ((0)),
	[matl_cost] [dbo].[CostPrcType] NULL CONSTRAINT [DF_tr_co_ship_matl_cost]  DEFAULT ((0)),
	[lbr_cost] [dbo].[CostPrcType] NULL CONSTRAINT [DF_tr_co_ship_lbr_cost]  DEFAULT ((0)),
	[fovhd_cost] [dbo].[CostPrcType] NULL CONSTRAINT [DF_tr_co_ship_fovhd_cost]  DEFAULT ((0)),
	[vovhd_cost] [dbo].[CostPrcType] NULL CONSTRAINT [DF_tr_co_ship_vovhd_cost]  DEFAULT ((0)),
	[out_cost] [dbo].[CostPrcType] NULL CONSTRAINT [DF_tr_co_ship_out_cost]  DEFAULT ((0)),
	[shipper_num] [dbo].[ShipperNumType] NULL,
	[do_num] [dbo].[DoNumType] NULL,
	[do_line] [dbo].[DoLineType] NULL CONSTRAINT [DF_tr_co_ship_do_line]  DEFAULT ((0)),
	[do_seq] [dbo].[DoSeqType] NULL CONSTRAINT [DF_tr_co_ship_do_seq]  DEFAULT ((0)),
	[NoteExistsFlag] [dbo].[FlagNyType] NOT NULL CONSTRAINT [DF_tr_co_ship_NoteExistsFlag]  DEFAULT ((0)),
	[RecordDate] [dbo].[CurrentDateType] NOT NULL CONSTRAINT [DF_tr_co_ship_RecordDate]  DEFAULT (getdate()),
	[RowPointer] [dbo].[RowPointerType] NOT NULL CONSTRAINT [DF_tr_co_ship_RowPointer]  DEFAULT (newid()),
	[CreatedBy] [dbo].[UsernameType] NOT NULL CONSTRAINT [DF_tr_co_ship_CreatedBy]  DEFAULT (suser_sname()),
	[UpdatedBy] [dbo].[UsernameType] NOT NULL CONSTRAINT [DF_tr_co_ship_UpdatedBy]  DEFAULT (suser_sname()),
	[CreateDate] [dbo].[CurrentDateType] NOT NULL CONSTRAINT [DF_tr_co_ship_CreateDate]  DEFAULT (getdate()),
	[InWorkflow] [dbo].[FlagNyType] NOT NULL CONSTRAINT [DF_tr_co_ship_InWorkflow]  DEFAULT ((0)),
	[pack_num] [dbo].[PackNumType] NULL,
	[orig_inv_num] [dbo].[InvNumType] NULL,
	[reason_text] [dbo].[FormEditorType] NULL
) ON [PRIMARY]
